import Client from "@/components/client";
import type { Metadata } from "next";
import "../themes/globals.css";

// const geistSans = localFont({
//   src: "../src/themes/fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="./favicon.png" />
      </head>
      <body
        suppressHydrationWarning={true}
        className={`--poppins antialiased bg-primary-color`}
      >
        <Client>
          {children}
        </Client>
      </body>
    </html>
  );
}
